//************************************************************************************
//*                                                                                  *
//* ===== DO NOT EDIT =====                                                          *
//* Any change will be overwritten                                                   *
//* Generated by github.com/boundedinfinity/enumer                                   *
//*                                                                                  *
//************************************************************************************

package enum_internal

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/boundedinfinity/go-commoner/slicer"
)

var (
	All = []MyByte{
		B0,
		B1,
		B2,
	}
)

func (t MyByte) String() string {
	return string(t)
}

func Parse(v byte) (MyByte, error) {
	f, ok := slicer.FindFn(All, func(x MyByte) bool {
		return MyByte(v) == x
	})

	if !ok {
		return f, ErrorV(v)
	}

	return f, nil
}

func Is(s byte) bool {
	return slicer.ContainsFn(All, func(v MyByte) bool {
		return byte(v) == s
	})
}

var ErrInvalid = errors.New("invalid enumeration type")

func ErrorV(v byte) error {
	return fmt.Errorf(
		"%w '%v', must be one of %v",
		ErrInvalid, v, slicer.Join(All, ","),
	)
}

func (t MyByte) MarshalJSON() ([]byte, error) {
	return json.Marshal(byte(t))
}

func (t *MyByte) UnmarshalJSON(data []byte) error {
	var v byte

	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}

	e, err := Parse(v)

	if err != nil {
		return err
	}

	*t = e

	return nil
}

func (t MyByte) MarshalYAML() (interface{}, error) {
	return byte(t), nil
}

func (t *MyByte) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var v byte

	if err := unmarshal(&v); err != nil {
		return err
	}

	e, err := Parse(v)

	if err != nil {
		return err
	}

	*t = e

	return nil
}
